# Exercise: Cleaning Data

Please load `supermarket_messy.csv` and complete the following tasks. Include your final code below. When you are done, click on `Run` > `Restart Kernel and Run All Cells...` and verify the output.
1. Change `Invoice ID` such that it contains only 9 digits number (for example: 750678428)
2. Change `State` such that any references to "Ohio" are replaced with "OH"
3. Change `State` such that any references to "Texas" are replaced with "TX"
4. Change `State` such that all letters are upper case
5. Change `City` such that the first letter is capitalized
6. Change `Customer type` such that all letters are lower case
7. Change `gross income` such that it contains only the actual gross income, like 3.82 (not gi), and is converted to a numeric variable
8. Change `Unit Price` such that it contains only the actual Unit Price, like 74.69 (not $), and is converted to a numeric variable
9. Remove any duplicate rows

In [3]:
import pandas as pd

In [4]:
SM=pd.read_csv('supermarket_messy.csv')

In [5]:
SM

,Invoice ID,State,City,Customer type,Product line,Unit price,gross income
0,(750)-67-8428,Ohio,yangon,Member,Health and beauty,$74.69,26.1415 gi
1,226-31-3081,FL,naypyitaw,Normal,Electronic accessories,$15.28,3.82 gi
2,(631)-41-3108,ga,yangon,Normal,Home and lifestyle,$46.33,16.2155 gi
3,(123)-19-1176,IL,yangon,Member,Health and beauty,$58.22,23.288 gi
4,(373)-73-7910,Ohio,yangon,Normal,Sports and travel,$86.31,30.2085 gi
...,...,...,...,...,...,...,...
86,362-58-8315,Texas,naypyitaw,Normal,Fashion accessories,$76.52,19.13 gi
87,(123)-19-1176,IL,yangon,Member,Health and beauty,$58.22,23.288 gi
88,510-95-6347,NY,mandalay,Member,Food and beverages,$48.52,7.278 gi
89,616-24-2851,FL,mandalay,Member,Fashion accessories,$17.87,3.574 gi
90,510-95-6347,NY,mandalay,Member,Food and beverages,$48.52,7.278 gi

In [6]:
SM.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 91 entries, 0 to 90
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Invoice ID     91 non-null     object
 1   State          91 non-null     object
 2   City           91 non-null     object
 3   Customer type  91 non-null     object
 4   Product line   91 non-null     object
 5   Unit price     91 non-null     object
 6   gross income   91 non-null     object
dtypes: object(7)
memory usage: 5.1+ KB

In [7]:
SM['Invoice ID']=SM['Invoice ID'].str.replace('[^0-9]','',regex=True)

In [8]:
SM['State']=SM['State'].str.replace('Ohio','OH', regex=False)

In [9]:
SM['State']=SM['State'].str.replace('Texas','TX', regex=False)

In [10]:
SM['State']=SM['State'].str.upper()

In [11]:
SM['City']=SM['City'].str.title()

In [12]:
SM['Customer type']=SM['Customer type'].str.lower()

In [13]:
SM['gross income']=SM['gross income'].str.replace('gi','',regex=False)

In [14]:
SM['Unit price']=SM['Unit price'].str.replace('$','',regex=False)

In [15]:
SM

,Invoice ID,State,City,Customer type,Product line,Unit price,gross income
0,750678428,OH,Yangon,member,Health and beauty,74.69,26.1415
1,226313081,FL,Naypyitaw,normal,Electronic accessories,15.28,3.82
2,631413108,GA,Yangon,normal,Home and lifestyle,46.33,16.2155
3,123191176,IL,Yangon,member,Health and beauty,58.22,23.288
4,373737910,OH,Yangon,normal,Sports and travel,86.31,30.2085
...,...,...,...,...,...,...,...
86,362588315,TX,Naypyitaw,normal,Fashion accessories,76.52,19.13
87,123191176,IL,Yangon,member,Health and beauty,58.22,23.288
88,510956347,NY,Mandalay,member,Food and beverages,48.52,7.278
89,616242851,FL,Mandalay,member,Fashion accessories,17.87,3.574
90,510956347,NY,Mandalay,member,Food and beverages,48.52,7.278

In [16]:
SM[SM.duplicated()].count()

Invoice ID       4
State            4
City             4
Customer type    4
Product line     4
Unit price       4
gross income     4
dtype: int64

In [17]:
SM=SM_clean=SM.drop_duplicates()

In [18]:
SM[SM.duplicated()].count()

Invoice ID       0
State            0
City             0
Customer type    0
Product line     0
Unit price       0
gross income     0
dtype: int64

In [19]:
SM

,Invoice ID,State,City,Customer type,Product line,Unit price,gross income
0,750678428,OH,Yangon,member,Health and beauty,74.69,26.1415
1,226313081,FL,Naypyitaw,normal,Electronic accessories,15.28,3.82
2,631413108,GA,Yangon,normal,Home and lifestyle,46.33,16.2155
3,123191176,IL,Yangon,member,Health and beauty,58.22,23.288
4,373737910,OH,Yangon,normal,Sports and travel,86.31,30.2085
...,...,...,...,...,...,...,...
82,480632856,GA,Naypyitaw,normal,Food and beverages,19.25,7.7
83,787560757,CA,Naypyitaw,member,Food and beverages,80.36,16.072
84,360395055,GA,Naypyitaw,member,Sports and travel,48.91,12.2275
85,730509884,GA,Naypyitaw,normal,Sports and travel,83.06,29.071
86,362588315,TX,Naypyitaw,normal,Fashion accessories,76.52,19.13

In [39]:
SM.to_csv('SM.csv', index=False)