# Dhruv Khanna

# Exercise: Handling Missing Values

## WHO

Answer the following question about `who.csv`, which contains data from the World Health Organization. Include your final code below. When you are done, click on `Run` > `Restart Kernel and Run All Cells...` and verify the output. 
- Q: Delete all rows with missing values. How many rows remain?
- A: 118

In [19]:
# Import modules
import pandas as pd

In [45]:
WHO= pd.read_csv('WHO.csv')

In [47]:
WHO

,country,countryid,continent,adole_fertility_p,adult_literacy_p,pc_GNI,p_sch_enrol_p_female,p_sch_enrol_p_male,tot_pop
0,Afghanistan,1,1,151.0,28.0,NaN,NaN,NaN,26088.0
1,Albania,2,2,27.0,98.7,6000.0,93.0,94.0,3172.0
2,Algeria,3,3,6.0,69.9,5940.0,94.0,96.0,33351.0
3,Andorra,4,2,NaN,NaN,NaN,83.0,83.0,74.0
4,Angola,5,3,146.0,67.4,3890.0,49.0,51.0,16557.0
...,...,...,...,...,...,...,...,...,...
197,Vietnam,198,6,25.0,90.3,2310.0,91.0,96.0,86206.0
198,West Bank and Gaza,199,1,NaN,NaN,NaN,NaN,NaN,NaN
199,Yemen,200,1,83.0,54.1,2090.0,65.0,85.0,21732.0
200,Zambia,201,3,161.0,68.0,1140.0,94.0,90.0,11696.0
201,Zimbabwe,202,3,101.0,89.5,NaN,88.0,87.0,13228.0

In [49]:
WHO.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 202 entries, 0 to 201
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   country               202 non-null    object
 1   countryid             202 non-null    int64
 2   continent             202 non-null    int64
 3   adole_fertility_p     177 non-null    float64
 4   adult_literacy_p      131 non-null    float64
 5   pc_GNI                178 non-null    float64
 6   p_sch_enrol_p_female  179 non-null    float64
 7   p_sch_enrol_p_male    179 non-null    float64
 8   tot_pop               189 non-null    float64
dtypes: float64(6), int64(2), object(1)
memory usage: 14.3+ KB

In [51]:
# Delete rows with missing values
W2=WHO.dropna()

In [53]:
W2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 118 entries, 1 to 200
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   country               118 non-null    object
 1   countryid             118 non-null    int64
 2   continent             118 non-null    int64
 3   adole_fertility_p     118 non-null    float64
 4   adult_literacy_p      118 non-null    float64
 5   pc_GNI                118 non-null    float64
 6   p_sch_enrol_p_female  118 non-null    float64
 7   p_sch_enrol_p_male    118 non-null    float64
 8   tot_pop               118 non-null    float64
dtypes: float64(6), int64(2), object(1)
memory usage: 9.2+ KB

## Sales

Answer the following question about `sales_exe.csv`, which contains data about sales. Include your final code below. When you are done, click on `Run` > `Restart Kernel and Run All Cells...` and verify the output. 
- Q: Delete the variable with the most missing values. Which variable did you delete?
- A: time

In [57]:
Sales= pd.read_csv('sales_exe.csv')

In [59]:
Sales

    Sales      time
0   271.5  1/1/2017
1   151.4  1/2/2017
2   188.6  1/3/2017
3   124.8  1/4/2017
4   185.8  1/5/2017
5   174.0  1/6/2017
6   237.3  1/7/2017
7   230.0  1/8/2017
8   198.3       NaN
9   128.4       NaN
10  342.0       NaN
11  191.4       NaN
12  199.8       NaN
13  155.0       NaN
14  215.6       NaN
15  278.8       NaN
16  196.9       NaN
17  292.5       NaN
18  231.5       NaN
19  309.1       NaN
20  295.4       NaN
21  427.1       NaN
22  270.0       NaN
23  347.8       NaN
24  345.2       NaN
25  445.9       NaN
26  321.4       NaN
27  444.8       NaN
28  406.8       NaN
29  442.9       NaN
30  581.0       NaN
31  413.1       NaN
32  687.5       NaN
33  480.8       NaN
34  586.8       NaN
35  652.4       NaN

In [61]:
Sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Sales   36 non-null     float64
 1   time    8 non-null      object
dtypes: float64(1), object(1)
memory usage: 708.0+ bytes

In [63]:
Sales.isna().sum()

Sales     0
time     28
dtype: int64

In [65]:
S1=Sales.drop(columns=['time'])

In [132]:
S1

    Sales
0   271.5
1   151.4
2   188.6
3   124.8
4   185.8
5   174.0
6   237.3
7   230.0
8   198.3
9   128.4
10  342.0
11  191.4
12  199.8
13  155.0
14  215.6
15  278.8
16  196.9
17  292.5
18  231.5
19  309.1
20  295.4
21  427.1
22  270.0
23  347.8
24  345.2
25  445.9
26  321.4
27  444.8
28  406.8
29  442.9
30  581.0
31  413.1
32  687.5
33  480.8
34  586.8
35  652.4

## CovidTotals

Answer the following questions about `covidtotals.csv`, which contains data about covid cases and deaths. Include your final code below. When you are done, click on `Run` > `Restart Kernel and Run All Cells...` and verify the output. 
- Q: What value did you use to replace missing values in `gdp_per_capita` and how did you derive that value?
- A: To get the value i used CT['gdp_per_capita'].median() The value is 12265.791000000001
- Q: What value did you use to replace missing values in `aged_65_older` and how did you derive that value?
- A: To get the value i used CT['aged_65_older'].median() the value is 6.224  
- Q: What value did you use to replace missing values in `region` and how did you derive that value?
- A: To get the value i used CT['region'].value_counts() and the value was'Eastern Europe'
  '

In [69]:
CT= pd.read_csv('covidtotals.csv')

In [71]:
CT

,iso_code,lastdate,location,total_cases_mill,total_deaths_mill,population,population_density,gdp_per_capita,aged_65_older,region
0,AFG,7/7/2021,Afghanistan,3314.321,139.102,38928341,54.422,1803.987,2.581,South Asia
1,ALB,7/7/2021,Albania,46061.922,853.430,2877800,104.871,11803.431,13.188,Eastern Europe
2,DZA,7/7/2021,Algeria,3261.770,86.338,43851043,17.348,13913.839,6.211,North Africa
3,AND,7/7/2021,Andorra,181466.382,1643.694,77265,163.755,NaN,NaN,NaN
4,AGO,7/7/2021,Angola,1201.566,28.144,32866268,23.890,5819.495,2.405,Central Africa
...,...,...,...,...,...,...,...,...,...,...
180,VEN,7/7/2021,Venezuela,9881.156,113.905,28435943,36.253,16745.022,6.614,South America
181,VNM,7/7/2021,Vietnam,240.244,1.048,97338583,308.127,6171.884,7.150,East Asia
182,YEM,7/7/2021,Yemen,232.482,45.732,29825968,53.508,1479.147,2.922,West Asia
183,ZMB,7/7/2021,Zambia,9192.962,142.407,18383956,22.995,3689.251,2.480,Southern Africa
184,ZWE,7/7/2021,Zimbabwe,4052.163,132.746,14862927,42.729,1899.775,2.822,Southern Africa

In [75]:
CT.isna().sum()

iso_code              0
lastdate              0
location              0
total_cases_mill      0
total_deaths_mill     0
population            0
population_density    0
gdp_per_capita        7
aged_65_older         8
region                6
dtype: int64

In [79]:
CT['gdp_per_capita'].median()

12265.791000000001

In [84]:
CT['gdp_per_capita'].fillna(CT['gdp_per_capita'].median())

0       1803.987
1      11803.431
2      13913.839
3      12265.791
4       5819.495
         ...
180    16745.022
181     6171.884
182     1479.147
183     3689.251
184     1899.775
Name: gdp_per_capita, Length: 185, dtype: float64

In [110]:
CT['aged_65_older'].median()

6.224

In [112]:
CT['aged_65_older'].fillna(CT['aged_65_older'].median())

0       2.581
1      13.188
2       6.211
3       6.224
4       2.405
        ...
180     6.614
181     7.150
182     2.922
183     2.480
184     2.822
Name: aged_65_older, Length: 185, dtype: float64

In [114]:
CT['region'].value_counts()

region
Eastern Europe     22
East Asia          17
Western Europe     17
West Asia          16
West Africa        16
East Africa        13
South America      12
Central Africa     11
Caribbean          11
South Asia          9
Southern Africa     9
Central America     7
Central Asia        6
North Africa        5
Oceania / Aus       5
North America       3
Name: count, dtype: int64

In [121]:
CT['region'].fillna(CT['region'].mode()[0])

0           South Asia
1       Eastern Europe
2         North Africa
3       Eastern Europe
4       Central Africa
            ...
180      South America
181          East Asia
182          West Asia
183    Southern Africa
184    Southern Africa
Name: region, Length: 185, dtype: object