# Exercise: Mutating Data

## Employees

Please load `employees_m.csv` and answer the following questions. Include your final code below. When you are done, click on `Run` > `Restart Kernel and Run All Cells...` and verify the output.
Please load `employees_m.csv` and answer the following questions. Include your final code below. When you are done, click on `Run` > `Restart Kernel and Run All Cells...` and verify the output.
- Q: Add a new column named `bonus`that contains `salary`*`bonus_percent`/100. What is the average of the new column?
- A:  9337.453565698492
- Q: Add a new column named `ave_logintime_pl`, "the average login time per login" that contains `total login time`/`# of logins`, What is the average of the new column?

- A:19.558
  
- Q: Extract 'Hour' from the 'last_login' variable. Add a new column named `Time Category` that contains 'Morning' if the `last_login` hour falls between six to twelve, 'Afternoon' if the `last_login` hour falls between twelve to eighteen, 'Evening' if the `last_login` hour falls between eighteen to midnight, and 'Night' if the `last_login` hour falls between midnight to six (**left inclusive**, for example, 6 <= hour < 12 is "Morning"). What is the count of values of the 'Time Category' variable? 

- A:
 Time Category
Afternoon    259
Night        249
Mornig       247
Evening      128

- Q: Add a new column named `Salary Category` that contains 'Low' if `salary` falls zero to q1, 'Below Average' if `salary` falls q1 to q2, 'Above Average' if `salary` falls q2 to q3, and 'High' if  `salary` falls q3 to q4, that is, max salary (**right inclusive**).  What is the count of values of the 'Salary Category' variable? 

- A:
  Salary Category
Below Average    249
High             249
Above Average    248
Max              248
- Save file as 'employees_new.csv'

In [4]:
import pandas as pd

In [5]:
EM=pd.read_csv('employees_m.csv')

In [6]:
EM

,first_name,gender,start_date,last_login,salary,bonus_percent,senior_management,team,# of logins,total login time
0,Douglas,Male,8/6/1993,12:42,97308.0,6.945,1.0,Marketing,4,112
1,Thomas,Male,3/31/1996,6:53,61933.0,4.170,1.0,NaN,5,75
2,Maria,Female,4/23/1993,11:17,130590.0,11.858,0.0,Finance,6,66
3,Jerry,Male,3/4/2005,13:00,138705.0,9.340,1.0,Finance,4,76
4,Larry,Male,1/24/1998,16:47,101004.0,1.389,1.0,Client Services,2,32
...,...,...,...,...,...,...,...,...,...,...
995,Henry,NaN,11/23/2014,6:09,132483.0,16.655,0.0,Distribution,2,56
996,Phillip,Male,1/31/1984,6:30,42392.0,19.675,0.0,Finance,9,225
997,Russell,Male,5/20/2013,12:39,96914.0,1.421,0.0,Product,7,112
998,Larry,Male,4/20/2013,16:45,60500.0,11.985,0.0,Business Development,5,120
999,Albert,Male,5/15/2012,18:24,129949.0,10.169,1.0,Sales,3,69

In [7]:
EM['ave_logintime_pl']=EM['total login time']/EM['# of logins']

In [8]:
EM['Bonus']=EM['salary']*EM['bonus_percent']/100

In [70]:
EM['Hours']=pd.to_datetime(EM['last_login']).dt.hour

/var/folders/_4/b9s2hms900bfwkkw9c61rv4w0000gn/T/ipykernel_85339/4200226725.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  EM['Hours']=pd.to_datetime(EM['last_login']).dt.hour

In [80]:
bins=[-1,6,12,18,24]

In [82]:
labels=['Night','Mornig','Afternoon','Evening']

In [84]:
EM['Time Category']=pd.cut(EM['Hours'],bins=bins, labels=labels, right=False)

In [86]:
EM['Time Category'].value_counts()

Time Category
Afternoon    259
Night        249
Mornig       247
Evening      245
Name: count, dtype: int64

In [13]:
EM['salary'].describe()

count       995.000000
mean      90939.771859
std       33743.381539
min       35013.000000
25%       62560.000000
50%       90427.000000
75%      118734.500000
max      229908.000000
Name: salary, dtype: float64

In [14]:
bins=[0,62560,90427,118734,229908]

In [15]:
labels=['Below Average','Above Average','High','Max']

In [16]:
EM['Salary Category']=pd.cut(EM['salary'],bins=bins, labels=labels, right=False)

In [17]:
EM

,first_name,gender,start_date,last_login,salary,bonus_percent,senior_management,team,# of logins,total login time,ave_logintime_pl,Bonus,Hours,Time Category,Salary Category
0,Douglas,Male,8/6/1993,12:42,97308.0,6.945,1.0,Marketing,4,112,28.0,6758.04060,12,Afternoon,High
1,Thomas,Male,3/31/1996,6:53,61933.0,4.170,1.0,NaN,5,75,15.0,2582.60610,6,Mornig,Below Average
2,Maria,Female,4/23/1993,11:17,130590.0,11.858,0.0,Finance,6,66,11.0,15485.36220,11,Mornig,Max
3,Jerry,Male,3/4/2005,13:00,138705.0,9.340,1.0,Finance,4,76,19.0,12955.04700,13,Afternoon,Max
4,Larry,Male,1/24/1998,16:47,101004.0,1.389,1.0,Client Services,2,32,16.0,1402.94556,16,Afternoon,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Henry,NaN,11/23/2014,6:09,132483.0,16.655,0.0,Distribution,2,56,28.0,22065.04365,6,Mornig,Max
996,Phillip,Male,1/31/1984,6:30,42392.0,19.675,0.0,Finance,9,225,25.0,8340.62600,6,Mornig,Below Average
997,Russell,Male,5/20/2013,12:39,96914.0,1.421,0.0,Product,7,112,16.0,1377.14794,12,Afternoon,High
998,Larry,Male,4/20/2013,16:45,60500.0,11.985,0.0,Business Development,5,120,24.0,7250.92500,16,Afternoon,Below Average
999,Albert,Male,5/15/2012,18:24,129949.0,10.169,1.0,Sales,3,69,23.0,13214.51381,18,Evening,Max

In [18]:
EM['ave_logintime_pl'].mean()

19.558

In [68]:
EM['Time Category'].isna().sum()

117

In [62]:
EM['Salary Category'].value_counts()

Salary Category
Below Average    249
High             249
Above Average    248
Max              248
Name: count, dtype: int64

In [21]:
EM['Bonus'].mean()

9337.453565698492

In [22]:
EM.to_csv('employees_new.csv')