# Exercise: Sorting and Slicing & Filtering

# <ins> Sorting and Slicing </ins>

## Mall_Customers

Please load `Mall_Customers.csv` and answer the following questions. Include your final code below. When you are done, click on `Run` > `Restart Kernel and Run All Cells...` and verify the output.
- Q: Extract the **20** clients with the highest `spending_score` and save the subset as `customer_subset1.csv`. What is the **average** of `annual_income` for the subset?
- A:69350
- Q: Extract the **100** clients with the lowest `spending_score`, keep only the columns `customer_id`, `gender`, and `annual_income`, and save the subset as `customer_subset2.csv`. What is the **count** of **"Female"** in `gender` for the subset?
- A: 56

In [5]:
import pandas as pd

In [6]:
MC= pd.read_csv('Mall_Customers.csv')

In [7]:
MC

     customer_id  gender  age  annual_income  spending_score
0              1    Male   19          15000              39
1              2    Male   21          15000              81
2              3  Female   20          16000               6
3              4  Female   23          16000              77
4              5  Female   31          17000              40
..           ...     ...  ...            ...             ...
195          196  Female   35         120000              79
196          197  Female   45         126000              28
197          198    Male   32         126000              74
198          199    Male   32         137000              18
199          200    Male   30         137000              83

[200 rows x 5 columns]

In [8]:
MC=MC.sort_values('spending_score', ascending=False)

In [9]:
MC

     customer_id  gender  age  annual_income  spending_score
11            12  Female   35          19000              99
19            20  Female   35          23000              98
145          146    Male   28          77000              97
185          186    Male   30          99000              97
127          128    Male   40          71000              95
..           ...     ...  ...            ...             ...
30            31    Male   60          30000               4
32            33    Male   53          33000               4
8              9    Male   64          19000               3
158          159    Male   34          78000               1
156          157    Male   37          78000               1

[200 rows x 5 columns]

In [10]:
MC=MC.reset_index(drop=True)

In [11]:
MC

     customer_id  gender  age  annual_income  spending_score
0             12  Female   35          19000              99
1             20  Female   35          23000              98
2            146    Male   28          77000              97
3            186    Male   30          99000              97
4            128    Male   40          71000              95
..           ...     ...  ...            ...             ...
195           31    Male   60          30000               4
196           33    Male   53          33000               4
197            9    Male   64          19000               3
198          159    Male   34          78000               1
199          157    Male   37          78000               1

[200 rows x 5 columns]

In [12]:
MC_subset=MC.head(20)

In [13]:
MC_subset

    customer_id  gender  age  annual_income  spending_score
0            12  Female   35          19000              99
1            20  Female   35          23000              98
2           146    Male   28          77000              97
3           186    Male   30          99000              97
4           128    Male   40          71000              95
5           168  Female   33          86000              95
6             8  Female   23          18000              94
7           142    Male   32          75000              93
8           164  Female   31          81000              93
9            42    Male   24          38000              92
10           34    Male   18          33000              92
11          174    Male   36          87000              92
12          124    Male   39          69000              91
13          194  Female   38         113000              91
14          180    Male   35          93000              90
15          150    Male   34          78000              90
16          156  Female   27          78000              89
17          136  Female   29          73000              88
18          184  Female   29          98000              88
19          152    Male   39          78000              88

In [14]:
MC_subset['annual_income'].mean()

69350.0

In [15]:
MC_subset.to_csv('customer_subset1.csv', index=False)

In [16]:
MC_subset2=MC.tail(100)

In [17]:
MC_subset2

     customer_id  gender  age  annual_income  spending_score
100          116  Female   19          65000              50
101          107  Female   66          63000              50
102          100    Male   20          61000              49
103           93    Male   48          60000              49
104           73  Female   60          50000              49
..           ...     ...  ...            ...             ...
195           31    Male   60          30000               4
196           33    Male   53          33000               4
197            9    Male   64          19000               3
198          159    Male   34          78000               1
199          157    Male   37          78000               1

[100 rows x 5 columns]

In [18]:
MC_SLICE=MC_subset2[['customer_id', 'gender', 'annual_income']]

In [19]:
MC_SLICE

     customer_id  gender  annual_income
100          116  Female          65000
101          107  Female          63000
102          100    Male          61000
103           93    Male          60000
104           73  Female          50000
..           ...     ...            ...
195           31    Male          30000
196           33    Male          33000
197            9    Male          19000
198          159    Male          78000
199          157    Male          78000

[100 rows x 3 columns]

In [20]:
MC_SLICE['gender'].value_counts()

gender
Female    56
Male      44
Name: count, dtype: int64

In [21]:
MC_SLICE.to_csv('customer_subset2.csv', index=False)

## newhousing

Please load `newhousing.csv` and answer the following questions. Include your final code below. When you are done, click on `Run` > `Restart Kernel and Run All Cells...` and verify the output.
- Q: Extract the **100** housing data with **the least** `price`, keep only the columns `price`, `area`, `bedrooms`, `bathrooms`, `stories`, and `parking` and save the subset as `housing_subset1.csv`. What is the **average** `price` for the subset?
-- A: 2675575.00
- Q: Extract the **250** housing data with **the highest** price` and save the subset as housings_subset2.csv`. What is the **average** `area` for the subset?
- A: 6317.520

In [24]:
NH= pd.read_csv('newhousing.csv')

In [25]:
NH

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,semi-furnished,unfurnished,areaperbedroom,bbratio
0,5250000,5500,3,2,1,1,0,1,0,0,0,0,1,0,1833.333333,0.666667
1,4480000,4040,3,1,2,1,0,0,0,0,1,0,1,0,1346.666667,0.333333
2,3570000,3640,2,1,1,1,0,0,0,0,0,0,0,1,1820.000000,0.500000
3,2870000,3040,2,1,1,0,0,0,0,0,0,0,0,1,1520.000000,0.500000
4,3570000,4500,2,1,1,0,0,0,0,0,0,0,0,0,2250.000000,0.500000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,4403000,4880,3,1,1,1,0,0,0,0,2,1,0,1,1626.666667,0.333333
541,2660000,2000,2,1,2,1,0,0,0,0,0,0,1,0,1000.000000,0.500000
542,4480000,8250,3,1,1,1,0,0,0,0,0,0,0,0,2750.000000,0.333333
543,5110000,11410,2,1,2,1,0,0,0,0,0,1,0,0,5705.000000,0.500000
544,4410000,3968,3,1,2,0,0,0,0,0,0,0,1,0,1322.666667,0.333333

In [26]:
NH_sort=NH.sort_values('price' , ascending=True)

In [27]:
NH_sort.reset_index()

,index,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,semi-furnished,unfurnished,areaperbedroom,bbratio
0,470,1750000,3850,3,1,2,1,0,0,0,0,0,0,0,1,1283.333333,0.333333
1,114,1750000,2910,3,1,1,0,0,0,0,0,0,0,0,0,970.000000,0.333333
2,410,1750000,3620,2,1,1,1,0,0,0,0,0,0,0,1,1810.000000,0.500000
3,11,1767150,2400,3,1,1,0,0,0,0,0,0,0,1,0,800.000000,0.333333
4,289,1820000,3000,2,1,1,1,0,1,0,0,2,0,0,1,1500.000000,0.500000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,201,11410000,7420,4,1,2,1,1,1,0,1,2,0,0,0,1855.000000,0.250000
541,467,12215000,7500,4,2,2,1,0,1,0,1,3,1,0,0,1875.000000,0.500000
542,469,12250000,9960,3,2,2,1,0,1,0,0,2,1,1,0,3320.000000,0.666667
543,232,12250000,8960,4,4,4,1,0,0,0,1,3,0,0,0,2240.000000,1.000000
544,35,13300000,7420,4,2,3,1,0,0,0,1,2,1,0,0,1855.000000,0.500000

In [28]:
NH_SLICE=NH_sort[[ 'price', 'area', 'bedrooms', 'bathrooms', 'stories', 'parking']]

In [29]:
NH_SLICE

        price  area  bedrooms  bathrooms  stories  parking
470   1750000  3850         3          1        2        0
114   1750000  2910         3          1        1        0
410   1750000  3620         2          1        1        0
11    1767150  2400         3          1        1        0
289   1820000  3000         2          1        1        2
..        ...   ...       ...        ...      ...      ...
201  11410000  7420         4          1        2        2
467  12215000  7500         4          2        2        3
469  12250000  9960         3          2        2        2
232  12250000  8960         4          4        4        3
35   13300000  7420         4          2        3        2

[545 rows x 6 columns]

In [30]:
NH_lowest=NH_SLICE.head(100)

In [31]:
NH_lowest

       price  area  bedrooms  bathrooms  stories  parking
470  1750000  3850         3          1        2        0
114  1750000  2910         3          1        1        0
410  1750000  3620         2          1        1        0
11   1767150  2400         3          1        1        0
289  1820000  3000         2          1        1        2
..       ...   ...       ...        ...      ...      ...
475  3150000  3500         2          1        1        0
356  3150000  9000         3          1        2        2
366  3150000  3986         2          2        1        1
490  3150000  3450         1          1        1        0
143  3150000  3069         2          1        1        1

[100 rows x 6 columns]

In [32]:
NH_lowest['price'].mean()

2675575.0

In [33]:
NH_lowest.to_csv('housing_subset1.csv')

In [34]:
NH_highest=NH_SLICE.tail(250)

In [35]:
NH_highest

        price  area  bedrooms  bathrooms  stories  parking
59    4543000  4990         4          2        2        0
153   4543000  4100         2          2        1        0
471   4550000  2550         3          1        2        0
292   4550000  3520         3          1        1        0
173   4550000  5360         3          1        2        2
..        ...   ...       ...        ...      ...      ...
201  11410000  7420         4          1        2        2
467  12215000  7500         4          2        2        3
469  12250000  9960         3          2        2        2
232  12250000  8960         4          4        4        3
35   13300000  7420         4          2        3        2

[250 rows x 6 columns]

In [36]:
NH_highest['area'].mean()

6317.52

In [37]:
NH_highest.to_csv('housing_subset2.csv')

# <ins>Filtering</ins>

## Employees Attrition

Please load `employee_attrition.csv` and answer the following questions. Include your final code below. When you are done, click on `Run` > `Restart Kernel and Run All Cells...` and verify the output.
- Q: Extract the employees from the **Life Sciences or Medical** EducationField and save the subset as`employees_subset1.csv`. What is the **count** of True in `OverTime` for the subset?
- A: 299
- Q: Extract the employees whose `DailyRate` is greater than **$1400** and `MaritalStatus` is **Single**, and save the subset as `employees_subset2.csv`. How many rows does the subset contain?
- A: 24

In [41]:
EA=pd.read_csv('employee_attrition.csv')

In [42]:
EA

,id,age,attrition,BusinessTravel,DailyRate,department,DistanceFromHome,education,EducationField,gender,MaritalStatus,NumCompaniesWorked,OverTime,TotalWorkingYears
0,1,41,True,Travel_Rarely,1102,Sales,1,2,Life Sciences,Female,Single,8,True,8
1,2,49,False,Travel_Frequently,279,Research & Development,8,1,Life Sciences,Male,Married,1,False,10
2,3,37,True,Travel_Rarely,1373,Research & Development,2,2,Other,Male,Single,6,True,7
3,4,33,False,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,Female,Married,1,True,8
4,5,27,False,Travel_Rarely,591,Research & Development,2,1,Medical,Male,Married,9,False,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,1466,36,False,Travel_Frequently,884,Research & Development,23,2,Medical,Male,Married,4,False,17
1466,1467,39,False,Travel_Rarely,613,Research & Development,6,1,Medical,Male,Married,4,False,9
1467,1468,27,False,Travel_Rarely,155,Research & Development,4,3,Life Sciences,Male,Married,1,True,6
1468,1469,49,False,Travel_Frequently,1023,Sales,2,3,Medical,Male,Married,2,False,17
1469,1470,34,False,Travel_Rarely,628,Research & Development,8,3,Medical,Male,Married,2,False,6

In [43]:
EA['OverTime'].value_counts()

OverTime
False    1054
True      416
Name: count, dtype: int64

In [44]:
ES1=EA[(EA['EducationField']=='Life Sciences') | (EA['EducationField']=='Medical')]

In [45]:
ES1

,id,age,attrition,BusinessTravel,DailyRate,department,DistanceFromHome,education,EducationField,gender,MaritalStatus,NumCompaniesWorked,OverTime,TotalWorkingYears
0,1,41,True,Travel_Rarely,1102,Sales,1,2,Life Sciences,Female,Single,8,True,8
1,2,49,False,Travel_Frequently,279,Research & Development,8,1,Life Sciences,Male,Married,1,False,10
3,4,33,False,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,Female,Married,1,True,8
4,5,27,False,Travel_Rarely,591,Research & Development,2,1,Medical,Male,Married,9,False,6
5,6,32,False,Travel_Frequently,1005,Research & Development,2,2,Life Sciences,Male,Single,0,False,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,1466,36,False,Travel_Frequently,884,Research & Development,23,2,Medical,Male,Married,4,False,17
1466,1467,39,False,Travel_Rarely,613,Research & Development,6,1,Medical,Male,Married,4,False,9
1467,1468,27,False,Travel_Rarely,155,Research & Development,4,3,Life Sciences,Male,Married,1,True,6
1468,1469,49,False,Travel_Frequently,1023,Sales,2,3,Medical,Male,Married,2,False,17
1469,1470,34,False,Travel_Rarely,628,Research & Development,8,3,Medical,Male,Married,2,False,6

In [46]:
ES1['OverTime'].value_counts()

OverTime
False    771
True     299
Name: count, dtype: int64

In [47]:
ES1.to_csv('employee_subset1.csv')

In [48]:
ES2=EA[(EA['DailyRate']>1400)&(EA['MaritalStatus']=='Single')]

In [49]:
ES2

,id,age,attrition,BusinessTravel,DailyRate,department,DistanceFromHome,education,EducationField,gender,MaritalStatus,NumCompaniesWorked,OverTime,TotalWorkingYears
51,52,28,True,Travel_Rarely,1434,Research & Development,5,4,Technical Degree,Male,Single,1,True,2
63,64,59,False,Travel_Rarely,1435,Sales,25,3,Life Sciences,Female,Single,7,False,28
110,111,51,False,Travel_Frequently,1456,Research & Development,1,4,Medical,Female,Single,3,False,23
146,147,30,False,Travel_Rarely,1427,Research & Development,2,1,Medical,Male,Single,0,False,6
165,166,50,False,Travel_Rarely,1452,Research & Development,11,3,Life Sciences,Female,Single,3,False,21
172,173,36,False,Travel_Frequently,1480,Research & Development,3,2,Medical,Male,Single,4,False,13
302,303,28,False,Travel_Rarely,1476,Research & Development,16,2,Medical,Male,Single,0,False,9
414,415,24,True,Travel_Rarely,1448,Sales,1,1,Technical Degree,Female,Single,1,True,6
524,525,34,False,Travel_Rarely,1442,Research & Development,9,3,Medical,Female,Single,1,False,9
569,570,36,False,Falsen-Travel,1434,Sales,8,4,Life Sciences,Male,Single,1,False,10
663,664,21,True,Travel_Rarely,1427,Research & Development,18,1,Other,Female,Single,1,False,1
665,666,47,False,Travel_Rarely,1454,Sales,2,4,Life Sciences,Female,Single,1,True,3
706,707,40,True,Falsen-Travel,1479,Sales,24,3,Life Sciences,Female,Single,4,True,22
913,914,45,True,Travel_Rarely,1449,Sales,2,3,Marketing,Female,Single,2,True,26
919,920,59,False,Travel_Rarely,1429,Research & Development,18,4,Medical,Male,Single,6,False,25
971,972,51,False,Travel_Rarely,1405,Research & Development,11,2,Technical Degree,Female,Single,3,False,29
1001,1002,37,False,Travel_Rarely,1462,Research & Development,11,3,Medical,Female,Single,4,False,8
1006,1007,49,True,Travel_Frequently,1475,Research & Development,28,2,Life Sciences,Male,Single,3,False,20
1022,1023,37,False,Falsen-Travel,1413,Research & Development,5,2,Technical Degree,Male,Single,0,False,7
1033,1034,31,True,Travel_Frequently,1445,Research & Development,1,5,Life Sciences,Female,Single,1,False,10
1046,1047,44,False,Travel_Rarely,1467,Research & Development,20,3,Life Sciences,Male,Single,1,False,6
1311,1312,18,False,Falsen-Travel,1431,Research & Development,14,3,Medical,Female,Single,1,False,0
1369,1370,28,True,Travel_Rarely,1475,Sales,13,2,Marketing,Female,Single,3,True,6
1391,1392,38,False,Travel_Rarely,1404,Sales,1,3,Life Sciences,Male,Single,4,False,20

In [50]:
ES2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 24 entries, 51 to 1391
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  24 non-null     int64
 1   age                 24 non-null     int64
 2   attrition           24 non-null     bool
 3   BusinessTravel      24 non-null     object
 4   DailyRate           24 non-null     int64
 5   department          24 non-null     object
 6   DistanceFromHome    24 non-null     int64
 7   education           24 non-null     int64
 8   EducationField      24 non-null     object
 9   gender              24 non-null     object
 10  MaritalStatus       24 non-null     object
 11  NumCompaniesWorked  24 non-null     int64
 12  OverTime            24 non-null     bool
 13  TotalWorkingYears   24 non-null     int64
dtypes: bool(2), int64(7), object(5)
memory usage: 2.5+ KB

## Airbnb_NY2019

Please load `airbnb_ny2019.csv` and answer the following questions. Include your final code below. When you are done, click on `Run` > `Restart Kernel and Run All Cells...` and verify the output.
- Q: Extract the airbnb that are located in **<ins>non</ins>-'Brooklyn'** `neighbourhood_group` and `last_review` date is after '2019-06-30' and save the subset as`airbnb_subset1.csv`. What is the most frequent room_type in the subset?
- A: Entire home/apt  
- Q: Extract the Airbnb from the Manhattan `neighbourhood_group` with `'number_of_reviews'` being greater than 400 and save the subset as `airbnb_subset2.csv`. What is the **average** `price` for the subset?
- A: 133.41666666666666

In [139]:
ABNB= pd.read_csv('airbnb_ny2019.csv')

In [141]:
ABNB

,id,host_id,neighbourhood_group,room_type,price,number_of_reviews,last_review,reviews_per_month,availability_365
0,2539,2787,Brooklyn,Private room,149,9,10/19/2018,0.21,365
1,2595,2845,Manhattan,Entire home/apt,225,45,5/21/2019,0.38,355
2,3647,4632,Manhattan,Private room,150,0,NaN,NaN,365
3,3831,4869,Brooklyn,Entire home/apt,89,270,7/5/2019,4.64,194
4,5022,7192,Manhattan,Entire home/apt,80,9,11/19/2018,0.10,0
...,...,...,...,...,...,...,...,...,...
48890,36484665,8232441,Brooklyn,Private room,70,0,NaN,NaN,9
48891,36485057,6570630,Brooklyn,Private room,40,0,NaN,NaN,36
48892,36485431,23492952,Manhattan,Entire home/apt,115,0,NaN,NaN,27
48893,36485609,30985759,Manhattan,Shared room,55,0,NaN,NaN,2
48894,36487245,68119814,Manhattan,Private room,90,0,NaN,NaN,23

In [145]:
ABNB['last_review']=pd.to_datetime(ABNB['last_review'], dayfirst=False, errors='coerce')

In [147]:
ABNB.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48895 entries, 0 to 48894
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   48895 non-null  int64
 1   host_id              48895 non-null  int64
 2   neighbourhood_group  48895 non-null  object
 3   room_type            48895 non-null  object
 4   price                48895 non-null  int64
 5   number_of_reviews    48895 non-null  int64
 6   last_review          38843 non-null  datetime64[ns]
 7   reviews_per_month    38843 non-null  float64
 8   availability_365     48895 non-null  int64
dtypes: datetime64[ns](1), float64(1), int64(5), object(2)
memory usage: 3.4+ MB

In [159]:
ABNB1=ABNB[(ABNB['neighbourhood_group']!='Brooklyn')&(ABNB['last_review']>'2019-06-30')]

In [161]:
ABNB1

,id,host_id,neighbourhood_group,room_type,price,number_of_reviews,last_review,reviews_per_month,availability_365
13,6021,11528,Manhattan,Private room,85,113,2019-07-05,0.91,333
17,7322,18946,Manhattan,Private room,140,260,2019-07-01,2.12,12
33,9783,32294,Manhattan,Private room,50,273,2019-07-01,2.37,359
39,12048,7549,Manhattan,Shared room,40,214,2019-07-05,1.81,188
46,12937,50124,Queens,Private room,130,248,2019-07-01,2.25,215
...,...,...,...,...,...,...,...,...,...
48732,36411407,33917435,Manhattan,Entire home/apt,150,1,2019-07-06,1.00,13
48782,36425863,83554966,Manhattan,Private room,129,1,2019-07-07,1.00,147
48790,36427429,257683179,Queens,Private room,45,1,2019-07-07,1.00,339
48799,36438336,211644523,Staten Island,Private room,235,1,2019-07-07,1.00,87
48805,36442252,273841667,Bronx,Entire home/apt,100,2,2019-07-07,2.00,40

In [165]:
ABNB1['room_type'].value_counts()

room_type
Entire home/apt    1524
Private room       1231
Shared room          57
Name: count, dtype: int64

In [167]:
ABNB1.to_csv('airbnb_subset1.csv')

In [169]:
ABNB2=ABNB[(ABNB['neighbourhood_group']=='Manhattan')&(ABNB['number_of_reviews']>400)]

In [171]:
ABNB2

,id,host_id,neighbourhood_group,room_type,price,number_of_reviews,last_review,reviews_per_month,availability_365
7,5178,8967,Manhattan,Private room,79,430,2019-06-24,3.47,220
225,58059,277379,Manhattan,Private room,60,458,2019-07-03,4.58,258
398,126443,627217,Manhattan,Entire home/apt,189,403,2019-07-07,4.10,201
1125,476983,277379,Manhattan,Private room,85,439,2019-07-05,5.12,238
1190,506121,2267153,Manhattan,Private room,72,451,2019-06-30,5.26,13
1879,834190,2369681,Manhattan,Private room,99,540,2019-07-06,6.95,179
2015,891117,4734398,Manhattan,Private room,49,594,2019-06-15,7.57,339
2030,903947,4734398,Manhattan,Private room,49,597,2019-06-23,7.72,342
2031,903972,4734398,Manhattan,Private room,49,607,2019-06-21,7.75,293
2092,945297,5074654,Manhattan,Private room,100,414,2019-06-22,5.39,231
2163,999248,273174,Manhattan,Entire home/apt,575,447,2019-07-01,5.89,207
5382,3888752,20116872,Manhattan,Entire home/apt,195,401,2019-06-30,6.76,178

In [173]:
ABNB2['price'].mean()

133.41666666666666

In [175]:
ABNB2.to_csv('airbnb_subset2.csv')